const fs = require("fs")
let c = fs.readFileSync("components/admin/AdminDashboard.tsx", "utf8")
c = c.replace(/\.sort\(\(a, b\)/g, ".sort((a: any, b: any)")
c = c.replace(/\.filter\(\(m\)/g, ".filter((m: any)")
c = c.replace(/\.filter\(\(s\)/g, ".filter((s: any)")
c = c.replace(/\.filter\(\(a\)/g, ".filter((a: any)")
c = c.replace(/\.filter\(\(j\)/g, ".filter((j: any)")
c = c.replace(/\.map\(\(a\)/g, ".map((a: any)")
c = c.replace(/\.map\(\(s\)/g, ".map((s: any)")
c = c.replace(/\.map\(\(m\)/g, ".map((m: any)")
c = c.replace(/\.map\(\(n\)/g, ".map((n: any)")
c = c.replace(/\.map\(\(o\)/g, ".map((o: any)")
c = c.replace(/\.map\(\(t\)/g, ".map((t: any)")
c = c.replace(/\.map\(\(j\)/g, ".map((j: any)")
c = c.replace(/\.map\(\(d\)/g, ".map((d: any)")
c = c.replace(/\.map\(\(qa\)/g, ".map((qa: any)")
c = c.replace(/\.map\(\(tab\)/g, ".map((tab: any)")
c = c.replace(/\.map\(\(opt\)/g, ".map((opt: any)")
c = c.replace(/\.map\(\(item\)/g, ".map((item: any)")
c = c.replace(/\.reduce\(\(acc, s\)/g, ".reduce((acc: number, s: any)")
c = c.replace(/signins\.map\(\(s: any\) => s\.user_id === m\.id\)/g, "signins.filter((s: any) => s.user_id === m.id)")
fs.writeFileSync("components/admin/AdminDashboard.tsx", c, "utf8")
console.log("Done")
