import { test, expect } from "@playwright/test"
import {
  login,
  openTab,
  deleteJob,
  findJobIdByName,
  ALLOWED_COMPANY,
} from "./helpers"

/**
 * Smoke suite: the four paths that must never be broken by a deploy.
 *
 * This runs against a live tenant, so the one spec that writes data names its
 * job obviously, deletes it in a finally block, and refuses to run at all if
 * the logged-in company is not the one the suite is pinned to.
 */

test.describe("smoke", () => {
  test("an admin can log in and reach the dashboard", async ({ page }) => {
    await login(page)

    // The nav landed on Today, which is the default admin view.
    await expect(page.getByRole("button", { name: "Today", exact: true })).toBeVisible()
    await expect(page.getByRole("heading", { name: "Today" })).toBeVisible()
  })

  test("an admin can create a job", async ({ page }) => {
    await login(page)

    // Guard: never write into a company this suite is not meant to touch.
    const company = await page.request.get("/api/admin/company")
    if (company.ok()) {
      const body = await company.json()
      const name: string = body?.company?.name ?? body?.name ?? ""
      expect(
        name,
        `refusing to create data: logged into "${name}", expected ${ALLOWED_COMPANY}`,
      ).toContain(ALLOWED_COMPANY)
    }

    const jobName = `E2E smoke ${Date.now()}`
    let jobId: string | null = null

    try {
      await openTab(page, "Jobs")
      await page.getByTestId("job-add").click()

      await page.getByTestId("job-name").fill(jobName)
      // The address field needs a Google Places selection, which a test cannot
      // drive. The coordinate paste field is the supported non-Places path and
      // sets the same lat/lng the form validates on.
      await page.getByTestId("job-coords").fill("51.857805,-4.300307")

      await page.getByTestId("job-save").click()

      await expect(page.getByText(jobName)).toBeVisible({ timeout: 30_000 })
      jobId = await findJobIdByName(page, jobName)
      expect(jobId, "created job should be readable back from the API").toBeTruthy()
    } finally {
      if (!jobId) jobId = await findJobIdByName(page, jobName)
      if (jobId) await deleteJob(page, jobId)
    }
  })

  test("an admin can generate an audit pack", async ({ page }) => {
    await login(page)
    await openTab(page, "Audit")

    const select = page.getByTestId("audit-job")
    await expect(select).toBeVisible()

    // Pick the first real job. A company with no jobs cannot produce a pack,
    // and that is a fixture problem rather than a regression, so say so.
    const options = await select.locator("option").all()
    const firstJob = options[1]
    test.skip(!firstJob, "no jobs in this company to build an audit pack from")
    await select.selectOption({ index: 1 })

    await page.getByTestId("audit-generate").click()

    // The pack renders its provenance footer once the report is built.
    await expect(page.getByText(/Generated by Vantro/i)).toBeVisible({ timeout: 90_000 })
  })

  test("the billing page loads", async ({ page }) => {
    await login(page)
    const res = await page.goto("/billing")
    expect(res?.status(), "billing should not error").toBeLessThan(400)
    await expect(page.getByRole("heading", { level: 1 })).toBeVisible()
  })
})
