import { NextResponse } from "next/server"
import { createClient, createServiceClient } from "@/lib/supabase/server"

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const formData = await request.formData()
  const to = formData.get('to') as string
  const jobName = formData.get('jobName') as string
  const reportRef = formData.get('reportRef') as string
  const file = formData.get('file') as File

  if (!to || !file) return NextResponse.json({ error: 'Missing fields' }, { status: 400 })

  if (process.env.RESEND_API_KEY) {
    const arrayBuffer = await file.arrayBuffer()
    const base64 = Buffer.from(arrayBuffer).toString('base64')

    await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${process.env.RESEND_API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        from: 'Vantro Reports <reports@getvantro.com>',
        to,
        subject: `Audit Report — ${jobName} — ${reportRef}`,
        html: `<div style="font-family:Arial,sans-serif;max-width:500px;margin:40px auto">
          <h2 style="color:#00a87a">Vantro Audit Report</h2>
          <p>Please find attached the audit report for <strong>${jobName}</strong>.</p>
          <p style="color:#666;font-size:12px">Report reference: ${reportRef}</p>
          <p style="color:#888;font-size:11px">Generated by Vantro — getvantro.com | CNNCTD Ltd (NI695071)</p>
        </div>`,
        attachments: [{
          filename: `Vantro-Audit-${jobName.replace(/\s+/g,'-')}.html`,
          content: base64,
          type: 'text/html'
        }]
      })
    })
  }

  return NextResponse.json({ success: true })
}